<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(FirebendTargetFrameworks)</TargetFrameworks>
    <IsPackable>false</IsPackable>
    <LangVersion>latestmajor</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoFixture.AutoMoq" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="GitHubActionsTestLogger">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="MSTest.TestAdapter" />
    <PackageReference Include="MSTest.TestFramework" />
    <PackageReference Include="coverlet.collector">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Neleus.LambdaCompare" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Jobba.Core\Jobba.Core.csproj" />
    <ProjectReference Include="..\Jobba.Cron\Jobba.Cron.csproj" />
    <ProjectReference Include="..\Jobba.MassTransit\Jobba.MassTransit.csproj" />
    <ProjectReference Include="..\Jobba.Redis\Jobba.Redis.csproj" />
    <ProjectReference Include="..\Jobba.Store.EF.Sqlite\Jobba.Store.EF.Sqlite.csproj" />
    <ProjectReference Include="..\Jobba.Store.EF\Jobba.Store.EF.csproj" />
    <ProjectReference Include="..\Jobba.Store.Mongo\Jobba.Store.Mongo.csproj" />
  </ItemGroup>

</Project>
