<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Version>12.0.1</Version>
    <LangVersion>latestmajor</LangVersion>
    <Nullable>disable</Nullable>
    <TargetFrameworks>$(FirebendTargetFrameworks)</TargetFrameworks>
    <Bumper>1</Bumper>
  </PropertyGroup>

  <PropertyGroup>
    <AssemblyTitle>Firebend Jobba Core</AssemblyTitle>
    <Description>Firebend Jobba</Description>
    <PackageTags>firebend;Jobba;job;scheduling;durable;background;jobs</PackageTags>
    <Authors>Firebend</Authors>
    <RepositoryUrl>https://github.com/firebend/Jobba</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/firebend/Jobba</PackageProjectUrl>
    <PackageIcon>nuget-image.png</PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AsyncKeyedLock" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>


</Project>
