<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(FirebendTargetFrameworks)</TargetFrameworks>
    <Version>13.0.0</Version>
    <LangVersion>latestmajor</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <AssemblyTitle>Firebend Jobba Store EF</AssemblyTitle>
    <Description>Firebend Jobba Store EF</Description>
    <PackageTags>firebend;Jobba;job;scheduling;durable;background;jobs;ef;data;store</PackageTags>
    <Authors>Firebend</Authors>
    <RepositoryUrl>https://github.com/firebend/Jobba</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/firebend/Jobba</PackageProjectUrl>
    <PackageIcon>nuget-image.png</PackageIcon>
  </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Jobba.Core\Jobba.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
      <PackageReference Include="Newtonsoft.Json" />
    </ItemGroup>

</Project>
