// <auto-generated />
using System;
using System.Collections.Generic;
using Jobba.Store.EF.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Jobba.Store.EF.Sqlite.Migrations
{
    [DbContext(typeof(JobbaDbContext))]
    [Migration("20241121000726_InitialScaffold")]
    partial class InitialScaffold
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Jobba.Core.Models.Entities.JobEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentNumberOfTries")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("EnqueuedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("FaultedReason")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOutOfRetry")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobName")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobParameters")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobParamsTypeName")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JobRegistrationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobState")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobStateTypeName")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobType")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("JobWatchInterval")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastProgressDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LastProgressPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxNumberOfTries")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ComplexProperty<Dictionary<string, object>>("SystemInfo", "Jobba.Core.Models.Entities.JobEntity.SystemInfo#JobSystemInfo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("ComputerName")
                                .HasColumnType("TEXT");

                            b1.Property<string>("OperatingSystem")
                                .HasColumnType("TEXT");

                            b1.Property<string>("SystemMoniker")
                                .HasColumnType("TEXT");

                            b1.Property<string>("User")
                                .HasColumnType("TEXT");
                        });

                    b.HasKey("Id");

                    b.HasIndex("JobRegistrationId");

                    b.HasIndex("Status");

                    b.ToTable("Jobs", "jobba");
                });

            modelBuilder.Entity("Jobba.Core.Models.Entities.JobProgressEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JobRegistrationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobState")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Progress")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("JobRegistrationId");

                    b.ToTable("JobProgress", "jobba");
                });

            modelBuilder.Entity("Jobba.Core.Models.JobRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CronExpression")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("DefaultJobWatchInterval")
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultMaxNumberOfTries")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultParams")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultState")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsInactive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobName")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobParamsType")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobStateType")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobType")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("NextExecutionDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("PreviousExecutionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZoneId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobName")
                        .IsUnique();

                    b.ToTable("JobRegistrations", "jobba");
                });

            modelBuilder.Entity("Jobba.Core.Models.Entities.JobEntity", b =>
                {
                    b.HasOne("Jobba.Core.Models.JobRegistration", null)
                        .WithMany()
                        .HasForeignKey("JobRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jobba.Core.Models.Entities.JobProgressEntity", b =>
                {
                    b.HasOne("Jobba.Core.Models.Entities.JobEntity", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jobba.Core.Models.JobRegistration", null)
                        .WithMany()
                        .HasForeignKey("JobRegistrationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
