<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(FirebendAppTargetFramework)</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit.RabbitMQ" />
    <PackageReference Include="MassTransit.Newtonsoft" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="Serilog.Extensions.Hosting" />
    <PackageReference Include="Serilog.Settings.Configuration" />
    <PackageReference Include="Serilog.Sinks.Console" />

  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Jobba.Core\Jobba.Core.csproj" />
    <ProjectReference Include="..\Jobba.Cron\Jobba.Cron.csproj" />
    <ProjectReference Include="..\Jobba.MassTransit\Jobba.MassTransit.csproj" />
    <ProjectReference Include="..\Jobba.Redis\Jobba.Redis.csproj" />
    <ProjectReference Include="..\Jobba.Store.EF\Jobba.Store.EF.csproj" />
    <ProjectReference Include="..\Jobba.Store.EF.Sqlite\Jobba.Store.EF.Sqlite.csproj" />
    <ProjectReference Include="..\Jobba.Store.EF.Sql\Jobba.Store.EF.Sql.csproj" />
    <ProjectReference Include="..\Jobba.Store.Mongo\Jobba.Store.Mongo.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="appsettings.Development.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Remove="jobba-sample.db" />
  </ItemGroup>

</Project>
