name: Build and test

on:
  push:
    branches:
      - '!main'
  pull_request:

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.101

      - name: Run dotnet format
        run: dotnet format jobba.sln --verify-no-changes

      - name: Install dependencies
        run: dotnet restore jobba.sln

      - name: Build
        run: dotnet build jobba.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test jobba.sln --logger GitHubActions --no-restore --verbosity normal --filter FullyQualifiedName\!~IntegrationTests
